### ISSUE TITLE
博客搬迁

### ISSUE THREAD

**Issue by Ruanxingzhi** [Ruanxingzhi/blog#11]
https://ruanx.pw/renew/

**Comment by Ruanxingzhi** [comment]
# 评论测试
`a test of Comments`

**Comment by riteme** [comment]
∫前排留名
<img width=32px height=32px src="https://www.gravatar.com/avatar/76b8f6097c85d35965da5eeb56e44ef9?s=250&d=mm&r=x"/>

**Comment by Ruanxingzhi** [comment]
@riteme 带哥你来辣

**Comment by ghost** [comment]
Ruanxingzhi学长，我提出一个诚恳的建议：建议把博客评论字体颜色调成亮色。不然需要选中才能看清。

**Comment by Ruanxingzhi** [comment]
@lyl913 您好，我无法复现这个问题，您是用的黑暗模式吗？

我这边是正常的：
![image.png](https://i.loli.net/2020/04/05/dGtwVo65PYjgKB8.png)

**Comment by ghost** [comment]
是的，我用的是macos的暗色模式，我查看过亮色模式了，没问题了。
抱歉给您带来了困扰qaq。
