### ISSUE TITLE
CTF RSA题解集

### ISSUE THREAD

**Issue by Ruanxingzhi** [Ruanxingzhi/blog#6]
https://ruanx.pw/rsa-solutions/

**Comment by ghost** [comment]
你好博主,为什么最后一道我用williams分不出来呢?
![QQ截图20200411162832.jpg](https://i.loli.net/2020/04/11/vg5EVA2OQkGLHod.jpg)

**Comment by Ruanxingzhi** [comment]
@chrisyang2003 我本地是可以分解的，您的Python版本号是多少？有没有安装gmpy2库？

**Comment by ghost** [comment]
好像primefac库只有2.7的版本呢所以在ubuntu上跑的...gmpy2当然有装



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "阮行止"<notifications@github.com&gt;; 
发送时间: 2020年4月11日(星期六) 下午5:15
收件人: "Ruanxingzhi/blog"<blog@noreply.github.com&gt;; 
抄送: "咖喱羊羊羊"<1017975501@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Ruanxingzhi/blog] CTF RSA题解集 (#6)





 
@chrisyang2003 我本地是可以分解的，您的Python版本号是多少？有没有安装gmpy2库？

**Comment by Ruanxingzhi** [comment]
诶……那很奇怪了啊，试试多等几分钟？

**Comment by ghost** [comment]
哈哈好的我再看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"阮行止"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 下午5:18
收件人:&nbsp;"Ruanxingzhi/blog"<blog@noreply.github.com&gt;;
抄送:&nbsp;"咖喱羊羊羊"<1017975501@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Ruanxingzhi/blog] CTF RSA题解集 (#6)





 
诶……那很奇怪了啊，试试多等几分钟？
